### ISSUE TITLE
Device pairing(iOS) timeout

### ISSUE THREAD

**Issue by thanhtungbk52** [tuya/tuya-home-ios-sdk-sample-swift#23]
I pulled "main" branch at commit 9627779
I configured my own appKey, secretKey, bundleId. I was able build success, do sign up and sign in successfully.
But when I tried to add device by EZ mode, The timeout occurs always.
`did received pairing result. step:4 pairingStep:token result:(null) error:Error Domain=com.thing.www Code=1512 "Timeout" UserInfo={NSLocalizedDescription=Timeout}`

I used Tuya app and successfully added my device using the same wifi network.

**Comment by taojingGino** [comment]
@thanhtungbk52 

For iOS 14.5 and later, we recommend that you use the AP mode instead of the Wi-Fi EZ mode. The former trumps the latter when it comes to the following aspects:

Compared with the Wi-Fi EZ mode, the AP mode results in a higher success rate, optimal reliability, and fewer compatibility requirements for mobile phones and routers.
The app built with Xcode 12.5 cannot send the EZ pairing data packets from iPhone that runs iOS 14.5 or later. In this case, the permission com.apple.developer.networking.multicast must be enabled for the app. This permission must be approved by Apple before it can be enabled. As a temporary solution, you can use an earlier Xcode version, but the AP mode is still recommended.

pls check this docment
https://developer.tuya.com/en/docs/app-development/iOS-network-ez?id=Kaixvcn8gy8o0
